;---------------------------------------------------------------------
; Timnigma Variables
;---------------------------------------------------------------------
[Variables]

; Font name and size for all skins
Font=Segoe UI
FontSize=10

; Tooltip Type - 0=Normal 1=Balloon
TTType=1

; PowerShell executable - change to powershell.exe if pwsh is not available
PowerShell=pwsh.exe

; HWiNFO version - HWiNFO64 or HWiNFO32
HWversion=HWiNFO64

; Color definitions - R, G, B, values from 0 to 255
ColorText=255,255,255
ColorRed=255,69,0
ColorGreen=152,251,152
ColorYellow=255,255,0

; Background bar color
BarColor=0,0,0

; Transparency of the background bar
BarTransparency=90

; Height of the background bar
BarHeight=44

; Transparency of the menu "hamburger icon"
MenuNormalAlpha=30
MenuHoverAlpha=200

; Network max upload and download - get values from speedtest.net
NetMaxDown=100
NetMaxUp=100

;Open Weather Map API key
MyOWMApiKey=
